services:
  web:
    build: .
    command: bin/web
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - RACK_KEY
      - TABLE_PREFIX
      - VUE_APP_GRAPHQL_HTTP
      - VUE_APP_GRAPHQL_WS
    health: /check
    port: https:3000
    scale:
      memory: 1000
