services:
  web:
    build: .
    command: bin/web
    domain: ${HOST}
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - HOST
      - LICENSE_KEY
      - RACK_KEY
      - SESSION_KEY
      - TABLE_PREFIX
      - WORKER_QUEUE
    health: /check
    port: https:3000
    scale:
      memory: 1500
  worker:
    build: .
    command: bin/worker
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - HOST
      - LICENSE_KEY
      - RACK_KEY
      - SESSION_KEY
      - TABLE_PREFIX
      - WORKER_QUEUE
    scale:
      memory: 1500
